import TerminalBox from '../components/TerminalBox.jsx'

/**
 * Docs page — long-form technical documentation for the Obscura project.
 * Aimed at developers exploring the codebase or evaluating the security model.
 */
export default function Docs() {
  return (
    <main className="page page--wide">
      <div className="page__inner">
        <p className="compose__tagline">Documentation</p>

        {/* ---------- Overview ---------- */}
        <TerminalBox title="Overview">
          <p className="docs__lead">
            Obscura is a zero-knowledge encrypted dead-drop messenger. Messages
            are encrypted in the sender's browser, stored only as opaque ciphertext,
            and atomically destroyed the first time they are read. Neither the
            server nor any operator can decrypt drops in transit or at rest.
          </p>
          <p className="docs__p">
            This page documents the architecture, threat model, API surface, and
            the AI features layered on top of the core protocol.
          </p>
        </TerminalBox>

        {/* ---------- Architecture ---------- */}
        <TerminalBox title="Architecture">
          <div className="docs__section">
            <h3 className="docs__h">Stack</h3>
            <ul className="docs__list">
              <li><strong>Backend:</strong> Python 3.12 · FastAPI · Uvicorn · Pydantic v2</li>
              <li><strong>Storage:</strong> Redis (drop blobs + rate-limit counters)</li>
              <li><strong>Frontend:</strong> Vite · React 18 · React Router · Web Crypto API</li>
              <li><strong>AI:</strong> Google Gemini API for sender-intent guardrail · Anthropic Claude for metadata-leak analysis</li>
              <li><strong>Identity:</strong> ULIDs for drops · HMAC-rotating IP hashes for rate limits</li>
            </ul>
          </div>

          <div className="docs__section">
            <h3 className="docs__h">Layout</h3>
            <pre className="docs__code">{`obscura/
├── backend/
│   ├── main.py              # FastAPI factory, security headers, CORS, SPA mount
│   ├── config.py            # Settings(BaseSettings) — all env vars
│   ├── dependencies.py      # Redis + rate-limit DI
│   ├── routers/             # /api/drops, /api/ai, /api/health
│   ├── models/              # Pydantic request/response schemas
│   └── services/
│       ├── drop_service.py  # ULID gen, atomic GETDEL burn
│       ├── ai_service.py    # Anthropic — metadata-leak warnings
│       └── intent_service.py# Gemini API — sender-intent guardrail
│
└── frontend/src/
    ├── pages/               # Compose, Receive, HowItWorks, Privacy, Docs
    ├── components/          # TerminalBox, FileDropZone, IntentWarning, …
    └── lib/
        ├── crypto.js        # AES-256-GCM via Web Crypto
        ├── envelope.js      # message + files bundle format
        ├── messageStats.js  # local fingerprint for intent guardrail
        └── api.js           # fetch wrappers
`}</pre>
          </div>
        </TerminalBox>

        {/* ---------- Encryption ---------- */}
        <TerminalBox title="Encryption protocol">
          <div className="docs__section">
            <h3 className="docs__h">Algorithm</h3>
            <p className="docs__p">
              AES-256-GCM with a 96-bit random IV per drop. Both key and IV are
              generated by <code>crypto.subtle</code> in the browser. The IV is
              prepended to the ciphertext, the whole blob is base64-encoded, and
              that string is what the server stores.
            </p>
          </div>
          <div className="docs__section">
            <h3 className="docs__h">Key transport</h3>
            <p className="docs__p">
              The key is base64url-encoded and appended to the share link as a
              URL fragment: <code>/drop/&#123;id&#125;#&#123;key&#125;</code>.
              Per RFC 3986, fragments are processed client-side only — they
              never appear in HTTP request lines, server logs, or referrer
              headers. The server therefore cannot learn the key even if it
              wants to.
            </p>
          </div>
          <div className="docs__section">
            <h3 className="docs__h">Burn-after-read</h3>
            <p className="docs__p">
              The recipient route uses Redis <code>GETDEL</code> — a single
              atomic operation that returns the value and deletes the key in
              one round trip. Two concurrent reads of the same drop result in
              exactly one 200 and one 404; the burn cannot race itself.
            </p>
          </div>
        </TerminalBox>

        {/* ---------- Envelope ---------- */}
        <TerminalBox title="Message envelope">
          <p className="docs__p">
            Drops can carry text, files, or both. The browser bundles them into
            a versioned JSON envelope <em>before</em> encryption, so the server
            still sees only opaque ciphertext.
          </p>
          <pre className="docs__code">{`{
  "v": 1,
  "message": "free-form text",
  "files": [
    { "name": "doc.pdf", "type": "application/pdf",
      "size": 12345, "data": "<base64>" }
  ]
}`}</pre>
          <p className="docs__p">
            Limits: 10 000 chars of text, 5 MB per file, 10 MB total
            attachments. Plaintext that does not parse as a v=1 envelope is
            treated as a plain text message — older drops keep working.
          </p>
        </TerminalBox>

        {/* ---------- API ---------- */}
        <TerminalBox title="HTTP API">
          <table className="docs__table">
            <thead>
              <tr>
                <th>Method</th><th>Path</th><th>Purpose</th><th>Rate limit</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>POST</td>
                <td><code>/api/drops</code></td>
                <td>Create a drop. Body: <code>&#123; ciphertext, ttl_seconds &#125;</code>.</td>
                <td>10 / min</td>
              </tr>
              <tr>
                <td>GET</td>
                <td><code>/api/drops/&#123;id&#125;</code></td>
                <td>Read &amp; burn. Returns ciphertext or 404 (identical body either way).</td>
                <td>20 / min</td>
              </tr>
              <tr>
                <td>POST</td>
                <td><code>/api/ai/intent-check</code></td>
                <td>Gemini API guardrail — accepts <em>only</em> message stats, not text.</td>
                <td>20 / min</td>
              </tr>
              <tr>
                <td>POST</td>
                <td><code>/api/ai/analyze</code></td>
                <td>Claude-backed metadata-leak analysis (anonymized session stats).</td>
                <td>5 / min</td>
              </tr>
              <tr>
                <td>GET</td>
                <td><code>/api/health</code></td>
                <td>Liveness + Redis ping.</td>
                <td>—</td>
              </tr>
            </tbody>
          </table>
        </TerminalBox>

        {/* ---------- AI features ---------- */}
        <TerminalBox title="AI features">
          <div className="docs__section">
            <h3 className="docs__h">Sender-intent guardrail · Google Gemini API</h3>
            <p className="docs__p">
              While the user types, the browser computes a statistical
              fingerprint of the plaintext — length, char-class counts, Shannon
              entropy, longest unbroken run, and pattern booleans (URL, email,
              phone, hex/base64, Luhn-passing card numbers). Only those numbers
              and booleans are POSTed to <code>/api/ai/intent-check</code>.
              Gemini classifies the likely category (password, API key, PII…)
              and returns a short headline + advice the UI shows above the
              composer. The plaintext never leaves the browser.
            </p>
            <p className="docs__p">
              Implementation: <code>backend/services/intent_service.py</code>
              calls the Gemini REST endpoint
              (<code>generativelanguage.googleapis.com/v1beta</code>) with
              <code>httpx</code> — no SDK required. The model is configurable
              via <code>GEMINI_MODEL</code> (default <code>gemini-2.5-flash</code>).
            </p>
          </div>
          <div className="docs__section">
            <h3 className="docs__h">Metadata-leak analysis · Anthropic Claude</h3>
            <p className="docs__p">
              On drop creation the backend can ship anonymized <em>session</em>
              statistics — hour of day, day of week, chosen TTL, ciphertext
              size, hourly platform traffic — to Claude. Claude flags
              behavioral fingerprints that could leak operational information
              even when the encryption itself holds (e.g. very short TTLs at
              odd hours, distinctive size distributions). Warnings are stored
              alongside the ciphertext and shown to the recipient.
            </p>
          </div>
          <div className="docs__section">
            <h3 className="docs__h">Graceful degradation</h3>
            <p className="docs__p">
              Both AI calls are advisory and bounded by short timeouts. Any
              exception falls back to an empty / info-level response — drop
              creation and reading are <em>never</em> blocked by AI.
            </p>
          </div>
        </TerminalBox>

        {/* ---------- Threat model ---------- */}
        <TerminalBox title="Threat model">
          <div className="docs__section">
            <h3 className="docs__h">In scope</h3>
            <ul className="docs__list">
              <li>Server compromise — operator cannot read past or future drops.</li>
              <li>Network observer — sees only ciphertext + size + timing.</li>
              <li>Replay / second-read — atomic GETDEL prevents reuse.</li>
              <li>Drop enumeration — ULIDs are 122-bit unguessable; 404 is identical for burned vs never-existed.</li>
            </ul>
          </div>
          <div className="docs__section">
            <h3 className="docs__h">Out of scope</h3>
            <ul className="docs__list">
              <li>Compromised sender or recipient device.</li>
              <li>Hostile browser extensions with DOM access.</li>
              <li>Link leakage through chat-app previews, browser history, or screenshots.</li>
              <li>Traffic-analysis correlation against your ISP records.</li>
            </ul>
          </div>
        </TerminalBox>

        {/* ---------- Configuration ---------- */}
        <TerminalBox title="Configuration">
          <p className="docs__p">All settings come from environment variables (or a <code>.env</code> file in dev):</p>
          <pre className="docs__code">{`REDIS_URL=redis://localhost:6379/0
CORS_ORIGINS=["http://localhost:5173"]
HMAC_SECRET=<32 random bytes hex>
ENVIRONMENT=development

# Anthropic — metadata-leak analysis (optional)
ANTHROPIC_API_KEY=sk-ant-...

# Gemini API — sender-intent guardrail (optional)
# Get a key at https://aistudio.google.com/apikey
GEMINI_API_KEY=...
GEMINI_MODEL=gemini-2.5-flash`}</pre>
          <p className="docs__p">
            Both AI integrations are optional. Missing credentials short-circuit
            to a no-op — the core encrypted-drop flow keeps working.
          </p>
        </TerminalBox>

        {/* ---------- Local dev ---------- */}
        <TerminalBox title="Running locally">
          <ol className="docs__list docs__list--ol">
            <li>Start Redis: <code>docker run -p 6379:6379 redis:7-alpine</code> (or Memurai on Windows).</li>
            <li>Backend: <code>python -m venv .venv</code> · <code>pip install -e ".[dev]"</code> · <code>uvicorn backend.main:app --reload --port 8000</code>.</li>
            <li>Frontend: <code>cd frontend</code> · <code>npm install</code> · <code>npm run dev</code> (Vite dev server with API proxy).</li>
            <li>Gemini API: get a key at <code>aistudio.google.com/apikey</code> and set <code>GEMINI_API_KEY</code>.</li>
            <li>Open <code>http://localhost:5173</code>.</li>
          </ol>
        </TerminalBox>

      </div>
    </main>
  )
}
